# -*- coding: utf-8 -*-
#
# Copyright (C) 2022 Graz University of Technology.
#
# Invenio-rdm-records is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: i18n:pull translations
on: workflow_dispatch # manually trigger

jobs:
  i18n-pull:
    runs-on: ubuntu-20.04
    env:
      PYTHON-VERSION: 3.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # setup python
      - name: Set up Python ${{ env.PYTHON-VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON-VERSION }}

      # install dependencies
      - name: Install dependencies
        run: |
          pip install -e ".[all]"  

      # install transifex client
      - name: transifex-client
        run: |
          pip install transifex-client

      # store token
      - name: store token
        run: |
          touch ~/.transifexrc
          echo [https://www.transifex.com] >> ~/.transifexrc
          echo api_hostname=https://api.transifex.com >> ~/.transifexrc
          echo hostname=https://www.transifex.com >> ~/.transifexrc
          echo password=${{ secrets.TRANSIFEX_TOKEN }} >> ~/.transifexrc
          echo username=api  >> ~/.transifexrc

      # pull all lang
      - name: pull translations
        run: |
          tx pull -a -f

      # remove transifex credential file
      - name: remove transifexrc file
        uses: JesseTG/rm@v1.0.2
        with:
          path: ~/.transifexrc

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: i18n:pulled translations
          title: i18n:pulled translations
          body: i18n:pulled translations
          branch: 101-translations-pull  # name of branch which PR is created from
          delete-branch: true  # delete branch once merged,closed
