# -*- coding: utf-8 -*-
#
# Copyright (C) 2022 Graz University of Technology.
#
# Invenio-RDM-Records is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: i18n:pull,extract,push translations
on: workflow_dispatch # manually trigger 

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # install transifex client
      - name: transifex-client
        run: |
          pip install transifex-client

      # store token
      - name: store token
        run: |
          touch ~/.transifexrc
          echo [https://www.transifex.com] >> ~/.transifexrc
          echo api_hostname=https://api.transifex.com >> ~/.transifexrc
          echo hostname=https://www.transifex.com >> ~/.transifexrc
          echo password=${{ secrets.TRANSIFEX_TOKEN }} >> ~/.transifexrc
          echo username=api  >> ~/.transifexrc

      # pull all lang
      - name: pull translations
        run: |
          tx pull -a

      # extract
      - name: extract_messages
        run: |
          python setup.py extract_messages

      # push
      - name: push_messages
        run: |
          tx push -s -t

      # remove transifex credential file
      - name: remove transifexrc file
        uses: JesseTG/rm@v1.0.2
        with:
          path: ~/.transifexrc

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: i18n:pull,extract,push translations
          title: i18n:pull,extract,push translations
          body: i18n:pull,extract,push translations
          branch: 101-translations  # name of branch which PR is created from
          delete-branch: true  # delete branch once merged,closed
